#ifndef EVENTS_H
#define EVENTS_H

enum {
    ID_INSTALL_APPLICATION = wxID_HIGHEST + 1,
    ID_INSTALL_DAEMON,
    ID_VIEW_LOGS,
    ID_REMOVE_APPLICATION,
    ID_CONNECTION_TIMER
};

#endif // EVENTS_H
